### PR TITLE
command-not-found: fix handling arguments with spaces (fixes #416)

### LINKED ISSUE #416: command-not-found: broken when original arguments contained spaces
When executing:
`gimp "Picture 1.jpg" "Picture 2.jpg"`
after the installation `command-not-found` will joing all the old arguments in a single string separated by spaces, so it would end up executing:
`gimp "Picture" "1.jpg" "Picture" "2.jpg"`

### PR DESCRIPTION
**Pull request by fernandoherreradelasheras**
Instead of joining the orignal arguments with spaces and executing
with g_spawn_command_line_sync use g_spawn_sync with a new argv[]
built from exec + arguments so we respect the original command line
arguments

### CODE REVIEW

File: contrib/command-not-found/pk-command-not-found.c [hunk 1]
```diff
@@ -870,7 +872,7 @@ main (int argc, char *argv[])
 				if (ret) {
 					ret = pk_cnf_install_package_id (package_ids[0]);
 					if (ret)
-						retval = pk_cnf_spawn_command (argv[1], &argv[2]);
+						retval = pk_cnf_spawn_command (argv[1], &argv[2], argc-2);
```
Comment (hughsie) [inline contrib/command-not-found/pk-command-not-found.c:875]: needs to be spaces around the `-` everywhere in the patch.

File: contrib/command-not-found/pk-command-not-found.c [hunk 2]
```diff
@@ -623,21 +623,23 @@ pk_cnf_get_config (void)
...
-	g_autofree gchar *cmd = NULL;
+  gchar *argv[arguments_count+2];
 
 	/* ensure program starts on a fresh line */
 	g_print ("\n");
 
-	args = g_strjoinv (" ", arguments);
-	cmd = g_strjoin (" ", exec, args, NULL);
-	if (!g_spawn_command_line_sync (cmd, NULL, NULL, &exit_status, &error)) {
+  argv[0] = (gchar*) exec;
```
Comment (hughsie) [inline contrib/command-not-found/pk-command-not-found.c:635]: tabs for intent please.

File: contrib/command-not-found/pk-command-not-found.c [hunk 3]
```diff
@@ -623,21 +623,23 @@ pk_cnf_get_config (void)
...
 
 static gint
-pk_cnf_spawn_command (const gchar *exec, gchar **arguments)
+pk_cnf_spawn_command (const gchar *exec, gchar **arguments, guint arguments_count)
 {
 	gint exit_status = EXIT_FAILURE;
 	g_autoptr(GError) error = NULL;
-	g_autofree gchar *args = NULL;
-	g_autofree gchar *cmd = NULL;
+  gchar *argv[arguments_count+2];
```
Comment (hughsie) [inline contrib/command-not-found/pk-command-not-found.c:630]: this needs to be `g_new0()` rather than VLA.

File: contrib/command-not-found/pk-command-not-found.c [hunk 4]
```diff
@@ -623,21 +623,24 @@ pk_cnf_get_config (void)
...
 	g_print ("\n");
 
-	args = g_strjoinv (" ", arguments);
-	cmd = g_strjoin (" ", exec, args, NULL);
-	if (!g_spawn_command_line_sync (cmd, NULL, NULL, &exit_status, &error)) {
+	argv = g_new0 (gchar *, arguments_count + 2);
+	argv[0] = (gchar*) exec;
+  for (guint i = 0; i <= arguments_count; i++) {
+    argv[1+i] = arguments[i];
+  }
```
Comment (hughsie) [inline contrib/command-not-found/pk-command-not-found.c:639]: tabs here, and then rebase all the patches to one commit and force push to the branch please.

File: contrib/command-not-found/pk-command-not-found.c [hunk 5]
```diff
@@ -623,21 +623,24 @@ pk_cnf_get_config (void)
...
+  if (!g_spawn_sync (NULL, argv, NULL, G_SPAWN_SEARCH_PATH, NULL, NULL,
+                      NULL, NULL, &exit_status, &error)) {
```
Comment (hughsie) [inline contrib/command-not-found/pk-command-not-found.c:641]: tabs here too.

**Comment by hughsie** [comment]
Thanks!
